import 'dart:html';
import 'dart:js' as JS;
import 'dart:convert' as Convert;
import '../lib/json_to_dart.dart';

void main() {
  final ButtonElement convertButton = document.querySelector('button[type="submit"]');
  final TextAreaElement textArea  = document.querySelector('textarea');
  final highlightedDartCode = document.querySelector('pre code.dart');
  final CheckboxInputElement usePrivateFieldsCheckbox = document.querySelector('#private-fields');
  final ButtonElement copyClipboardButton = document.querySelector('#copy-clipboard');
  final TextAreaElement hiddenElement = document.querySelector('#hidden-dart');
  copyClipboardButton.onClick.listen((MouseEvent event) {
   event.preventDefault();
   event.stopPropagation();
   if (!copyClipboardButton.disabled) {
     hiddenElement.select();
     document.execCommand("Copy");
   }
  });
  convertButton.onClick.listen((MouseEvent event) {
    event.preventDefault();
    event.stopPropagation();
    var syntaxError = false;
    final json = textArea.value;
    try {
      Convert.json.decode(json);
    } catch (e) {
      syntaxError = true;
      window.alert('The json provider has syntax errors');
    }
    if (!syntaxError) {
      final modelGenerator = new ModelGenerator('Autogenerated', usePrivateFieldsCheckbox.checked);
      String dartCode;
      try {
        dartCode = modelGenerator.generateDartClasses(json);
      } catch (e) {
        window.alert('There was a library error generating the dart code');
        print(e);
      }
      hiddenElement.value = dartCode;
      highlightedDartCode.text = dartCode;
      copyClipboardButton.attributes.remove('disabled');
      JS.context['hljs'].callMethod('highlightBlock', [highlightedDartCode]);
    } else {
      hiddenElement.value = '';
      highlightedDartCode.text = '';
      copyClipboardButton.attributes.putIfAbsent('disabled', () => 'disabled');
    }
  });
}